### ISSUE TITLE
Please Add a description whats needed for compilation

### ISSUE THREAD

**Issue by Tsubajashi** [jkendall327/waifu2x-ncnn-vulkan-gui#24]
Hi!
i wanted to ask, if it is possible that you can add an "Compiling" Entry in the readme, so that people who never used .Net know how to compile it ourself.
Or, if there would be rpm packages for ease of use.

**Comment by jkendall327** [comment]
Hi there,

Sorry for the long wait, I've just added some extra detail to the README which should cover this. I am interested in making more packages for the app, but I'm new to the Linux ecosystem and have found it very confusing so far.

Hope you enjoy the program!
